export const documents = [
  {
    id: 1,
    releaseDate: '1-1-2025',
    title:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
    type: 'Công văn',
  },
  {
    id: 2,
    releaseDate: '1-1-2025',
    title: 'Chào mừng',
    type: 'Công văn',
  },
  {
    id: 3,
    releaseDate: '1-1-2025',
    title: 'Hướng dẫn Lorem Ipsum is simply dumm',
    type: 'Hướng dẫn',
  },
  {
    id: 4,
    releaseDate: '1-1-2025',
    title: 'test4',
    type: 'Hướng dẫn',
  },
  {
    id: 5,
    releaseDate: '1-1-2025',
    title: 'test5',
    type: 'Kế hoạch',
  },
  {
    id: 6,
    releaseDate: '1-1-2025',
    title: 'test6',
    type: 'Kế hoạch',
  },
  {
    id: 7,
    releaseDate: '1-1-2025',
    title: 'test7',
    type: 'Kế hoạch liên tịch',
  },
  {
    id: 8,
    releaseDate: '1-1-2025',
    title: 'test8',
    type: 'Kế hoạch liên tịch',
  },
  {
    id: 9,
    releaseDate: '1-1-2025',
    title: 'test9',
    type: 'Kế hoạch liên tịch',
  },
  {
    id: 10,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thông báo',
  },
  {
    id: 11,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thông báo',
  },
  {
    id: 12,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thông báo',
  },
  {
    id: 13,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thông báo',
  },
  {
    id: 14,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thông báo',
  },
  {
    id: 15,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thông báo',
  },
  {
    id: 16,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 17,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 18,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 19,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 20,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 21,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 22,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 23,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 24,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 25,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 26,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 27,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 28,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 29,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 30,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 31,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 32,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 33,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 34,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 35,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 36,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 37,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 38,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 39,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 40,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 41,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 42,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 43,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 44,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 45,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 46,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 47,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 48,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 49,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 50,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 50,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 51,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 52,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 53,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 54,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 55,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 56,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 57,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 58,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 59,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
  {
    id: 60,
    releaseDate: '1-1-2025',
    title: 'test',
    type: 'Thư mời',
  },
]
