export const DOC_CATEGORY = {
  BAO_CAO: 'BAO_CAO',
  CHUONG_TRINH: 'CHUONG_TRINH',
  CONG_VAN: 'CONG_VAN',
  HUONG_DAN: 'HUONG_DAN',
  KE_HOACH: 'KE_HOACH',
  KE_HOACH_LIEN_TICH: 'KE_HOACH_LIEN_TICH',
  QUYET_DINH: 'QUYET_DINH',
  THONG_BAO: 'THONG_BAO',
  THU_MOI: 'THU_MOI',
}
export default DOC_CATEGORY
