export enum ROLE_TITLE {
  MAIN = 'MAIN',
  ASSISTANT = 'ASSISTANT',
}

export enum POST_CATEGORY {
  GIOI_THIEU = 'GIOI_THIEU',
  SINH_VIEN_5_TOT = 'SINH_VIEN_5_TOT',
  CAU_CHUYEN_DEP = 'CAU_CHUYEN_DEP',
  TINH_NGUYEN = 'TINH_NGUYEN',
  NCKH = 'NCKH',
  HO_TRO_SINH_VIEN = 'HO_TRO_SINH_VIEN',
  XAY_DUNG_HOI = 'XAY_DUNG_HOI',
}
