export const PATH_NAME = {
  HOME: '/',
  GIOI_THIEU: '/gioi-thieu',
  SVNT: '/sinh-vien-5-tot',
  CAU_CHUYEN_DEP: '/cau-chuyen-dep',
  TINH_NGUYEN: '/tinh-nguyen',
  NCKH: '/nckh',
  HO_TRO_SINH_VIEN: '/ho-tro-sinh-vien',
  XAY_DUNG_HOI: '/xay-dung-hoi',
  HE_THONG_VAN_BAN: '/he-thong-van-ban',
  DANG_NHAP: '/dang-nhap',
  QUAN_LY_BAI_DANG: '/admin/quan-ly-bai-dang',
  QUAN_LY_TAI_LIEU: '/admin/quan-ly-tai-lieu',
  CAP_TAI_KHOAN: '/superuser/cap-tai-khoan',
}
