import { Admin } from '@/models'

export const listAdmin: Admin[] = [
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
  {
    _id: '1',
    email: 'admin@email.com',
    name: 'admin',
    phoneNumber: '0123456789',
    role: 'Admin',
  },
]
